using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace RollTheDice.Configs;

public class RarityConfig
{
	[JsonPropertyName("tier_weights")]
	public Dictionary<string, float> TierWeights { get; set; } = new Dictionary<string, float>
	{
		{ "common", 70f },
		{ "rare", 20f },
		{ "epic", 6f },
		{ "legendary", 2f },
		{ "combo", 2f },
	};

	[JsonPropertyName("broadcast_legendary")]
	public bool BroadcastLegendary { get; set; } = true;

	[JsonPropertyName("dice_tier")]
	public Dictionary<string, string> DiceTier { get; set; } = new Dictionary<string, string>
	{
		// ── 传说 legendary ──────────────────────────────────────────────
		{ "Fate", "legendary" },
		{ "God", "legendary" },
		{ "Ragnarok", "legendary" },
		{ "FourHorsemen", "legendary" },
		{ "Cthulhu", "legendary" },
		{ "DragonSoul", "legendary" },
		{ "FourtyTwo", "legendary" },
		{ "WolfKing", "legendary" },

		// ── combo ──────────────────────────────────────────────────────
		{ "BeyondHeaven", "combo" },
		{ "DeathKnightComplete", "combo" },
		{ "FireDragon", "combo" },
		{ "IceDragon", "combo" },
		{ "Phoenix", "combo" },
		{ "RadarStation", "combo" },

		// ── 史诗 epic ──────────────────────────────────────────────────
		{ "WheelOfFate", "epic" },
		{ "NukeLeak", "epic" },
		{ "Singularity", "epic" },
		{ "BlackHole", "epic" },
		{ "WhiteHole", "epic" },
		{ "GravityWell", "epic" },
		{ "Titanfall", "epic" },
		{ "Combo", "epic" },
		{ "PainConverter", "epic" },
		{ "DecoyDummy", "epic" },
		{ "Drone", "epic" },
		{ "Dragonborn", "epic" },
		{ "Void", "epic" },
		{ "ThunderChain", "epic" },
		{ "Reincarnation", "epic" },
		{ "Respawn", "epic" },
		{ "InfiniteProliferation", "epic" },
		{ "DivineResurrection", "epic" },
		{ "Necromancer", "epic" },
		{ "Emperor", "epic" },
		{ "Gaia", "epic" },
		{ "Cutter", "epic" },
		{ "Thorns", "epic" },
		{ "GuardianAngel", "epic" },
		{ "Prophet", "epic" },
		{ "Forsaken", "epic" },
		{ "Pope", "epic" },
		{ "World", "epic" },
		{ "DeathKnight", "epic" },
		{ "Taotie", "epic" },

		// ── 稀有 rare ──────────────────────────────────────────────────
		{ "ResetOnReload", "rare" },
		{ "DamageMultiplier", "rare" },
		{ "IncreaseSpeed", "rare" },
		{ "Regeneration", "rare" },
		{ "Shield", "rare" },
		{ "HighGravity", "rare" },
		{ "DeagleKing", "rare" },
		{ "SniperElite", "rare" },
		{ "PistolMaster", "rare" },
		{ "GrenadeKing", "rare" },
		{ "LongerFlashes", "rare" },
		{ "Twilight", "rare" },
		{ "BoneMaggot", "rare" },
		{ "ReturnToSender", "rare" },
		{ "SwordSaint", "rare" },
		{ "Bank", "rare" },
		{ "Vampire", "rare" },
		{ "NoRecoil", "rare" },
		{ "GunGod", "rare" },
		{ "Hermit", "rare" },
		{ "Satellite", "rare" },
		{ "Countdown", "rare" },
		{ "Kinship", "rare" },
		{ "InfiniteAmmo", "rare" },
		{ "Berserker", "rare" },
		{ "SmokeVision", "rare" },
		{ "Evasion", "rare" },
		{ "IceBeam", "rare" },
		{ "SpeedOnKill", "rare" },
		{ "PoisonBlade", "rare" },
		{ "Adrenaline", "rare" },
		{ "Bounty", "rare" },
		{ "Lucky", "rare" },
		{ "SmokeBomb", "rare" },
		{ "RoyalBarrier", "rare" },
		{ "C4Expert", "rare" },
		{ "Knight", "rare" },
		{ "HangedMan", "rare" },
		{ "Giant", "rare" },
		{ "FireLord", "rare" },
		{ "Jester", "rare" },
		{ "Empress", "rare" },
		{ "Afterimage", "rare" },
		{ "LaserCage", "rare" },
		{ "DivinePunishment", "rare" },
		{ "SoulEater", "rare" },
		{ "IronHead", "rare" },
		{ "WeaponRoulette", "rare" },
		{ "Glutton", "rare" },
		{ "RouletteGambler", "rare" },
		{ "Izayoi", "rare" },
		{ "Goddess", "rare" },
		{ "Skyline", "rare" },
		{ "ReverseCausality", "rare" },
		{ "Frostmourne", "rare" },
		{ "ChaosStorm", "rare" },
		{ "FrontlineBeast", "rare" },
		{ "Yagorou", "rare" },
		{ "Mimic", "rare" },
		{ "DuskDawn", "rare" },
		{ "Evolution", "rare" },
		{ "Rally", "rare" },
		{ "Guillotine", "rare" },

		// ── 普通 common ────────────────────────────────────────────────
		{ "FogOfWar", "common" },
		{ "Jammer", "common" },
		{ "NoExplosives", "common" },
		{ "PlayAsChicken", "common" },
		{ "Deaf", "common" },
		{ "Martyrdom", "common" },
		{ "Pickpocket", "common" },
		{ "Payback", "common" },
		{ "Fireball", "common" },
		{ "ImposterSyndrome", "common" },
		{ "Cupid", "common" },
		{ "ToxicSmoke", "common" },
		{ "Capitalist", "common" },
		{ "GunHealer", "common" },
		{ "Mosquito", "common" },
		{ "Tactician", "common" },
		{ "Priest", "common" },
		{ "Fool", "common" },
		{ "RepulsionField", "common" },
		{ "RadarJammer", "common" },
		{ "JumpHeal", "common" },
		{ "ShadowWarrior", "common" },
		{ "Disarm", "common" },
		{ "WASDChaos", "common" },
		{ "Gargoyle", "common" },
		{ "Lottery", "common" },
		{ "Miser", "common" },
		{ "Redemption", "common" },
		{ "Traitor", "common" },
		{ "Eclipse", "common" },
		{ "Awakener", "common" },
		{ "Paladin", "common" },
		{ "Trickster", "common" },
		{ "Sacrifice", "common" },
		{ "Plague", "common" },
		{ "Nirvana", "common" },
		{ "Karma", "common" },
		{ "SacrificeSelf", "common" },
		{ "Synced", "common" },
		{ "DeadHand", "common" },
		{ "HotPotato", "common" },
		{ "InfoHole", "common" },
		{ "LoanShark", "common" },
		{ "MagneticPulse", "common" },
		{ "Overheat", "common" },
		{ "SlyFox", "common" },
		{ "Parasite", "common" },
		{ "Bugle", "common" },
		{ "Prayer", "common" },
		{ "Corona", "common" },
		{ "Heaven", "common" },
		{ "Nightglow", "common" },
		{ "Fibonacci", "common" },
		{ "Amber", "common" },
		{ "Wolf", "common" },
		{ "Anatomist", "common" },
		{ "Crouch", "common" },
		{ "LastStand", "common" },
		{ "ReloadGap", "common" },
		{ "Echo", "common" },
		{ "Curse", "common" },
		{ "Teneril", "common" },
	};
}
