using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace RollTheDice.Configs;

public class RarityConfig
{
    [JsonPropertyName("tier_weights")]
    public Dictionary<string, float> TierWeights { get; set; } = new Dictionary<string, float>
    {
        { "common", 70f },
        { "rare", 20f },
        { "epic", 6f },
        { "legendary", 2f },
        { "combo", 2f },
    };

    [JsonPropertyName("broadcast_legendary")]
    public bool BroadcastLegendary { get; set; } = true;

    [JsonPropertyName("dice_tier")]
    public Dictionary<string, string> DiceTier { get; set; } = new Dictionary<string, string>
    {
        // -- 传说 legendary --
        { "Cthulhu", "legendary" },
        { "Fate", "legendary" },
        { "FourHorsemen", "legendary" },
        { "God", "legendary" },
        { "Ragnarok", "legendary" },
        { "WheelOfFate", "legendary" },
        { "WolfKing", "legendary" },
        { "World", "legendary" },

        // -- combo --
        { "BeyondHeaven", "combo" },
        { "DeathKnightComplete", "combo" },
        { "FireDragon", "combo" },
        { "IceDragon", "combo" },
        { "Phoenix", "combo" },
        { "RadarStation", "combo" },

        // -- 史诗 epic --
        { "Awakener", "epic" },
        { "DeathKnight", "epic" },
        { "DivineResurrection", "epic" },
        { "Dragonborn", "epic" },
        { "Drone", "epic" },
        { "Emperor", "epic" },
        { "Forsaken", "epic" },
        { "FourtyTwo", "epic" },
        { "GunGod", "epic" },
        { "ImposterSyndrome", "epic" },
        { "InfiniteProliferation", "epic" },
        { "Izayoi", "epic" },
        { "Kinship", "epic" },
        { "Mosquito", "epic" },
        { "NukeLeak", "epic" },
        { "Pope", "epic" },
        { "Prophet", "epic" },
        { "Reincarnation", "epic" },
        { "RoyalBarrier", "epic" },
        { "Singularity", "epic" },
        { "SwordSaint", "epic" },
        { "Tactician", "epic" },
        { "Taotie", "epic" },
        { "Titanfall", "epic" },
        { "Void", "epic" },

        // -- 稀有 rare --
        { "Afterimage", "rare" },
        { "Berserker", "rare" },
        { "BlackHole", "rare" },
        { "BoneMaggot", "rare" },
        { "C4Expert", "rare" },
        { "ChaosStorm", "rare" },
        { "Combo", "rare" },
        { "Countdown", "rare" },
        { "DeagleKing", "rare" },
        { "DivinePunishment", "rare" },
        { "DragonSoul", "rare" },
        { "DuskDawn", "rare" },
        { "Empress", "rare" },
        { "Evasion", "rare" },
        { "Fibonacci", "rare" },
        { "FireLord", "rare" },
        { "Fool", "rare" },
        { "FrontlineBeast", "rare" },
        { "Giant", "rare" },
        { "Glutton", "rare" },
        { "Goddess", "rare" },
        { "GravityWell", "rare" },
        { "GrenadeKing", "rare" },
        { "GuardianAngel", "rare" },
        { "Guillotine", "rare" },
        { "Heaven", "rare" },
        { "Hermit", "rare" },
        { "IceBeam", "rare" },
        { "Knight", "rare" },
        { "LaserCage", "rare" },
        { "MagneticPulse", "rare" },
        { "Martyrdom", "rare" },
        { "Mimic", "rare" },
        { "Necromancer", "rare" },
        { "Nightglow", "rare" },
        { "Nirvana", "rare" },
        { "PainConverter", "rare" },
        { "Parasite", "rare" },
        { "PlayAsChicken", "rare" },
        { "Prayer", "rare" },
        { "Rally", "rare" },
        { "RepulsionField", "rare" },
        { "ResetOnReload", "rare" },
        { "Respawn", "rare" },
        { "ReturnToSender", "rare" },
        { "ReverseCausality", "rare" },
        { "RouletteGambler", "rare" },
        { "Sacrifice", "rare" },
        { "Satellite", "rare" },
        { "Shield", "rare" },
        { "Skyline", "rare" },
        { "SmokeBomb", "rare" },
        { "SmokeVision", "rare" },
        { "SniperElite", "rare" },
        { "SoulEater", "rare" },
        { "SpeedOnKill", "rare" },
        { "Twilight", "rare" },
        { "Vampire", "rare" },
        { "WASDChaos", "rare" },
        { "WhiteHole", "rare" },
        { "Yagorou", "rare" },

        // -- 普通 common --
        { "Adrenaline", "common" },
        { "Amber", "common" },
        { "Anatomist", "common" },
        { "Bank", "common" },
        { "Bounty", "common" },
        { "Bugle", "common" },
        { "Capitalist", "common" },
        { "Corona", "common" },
        { "Crouch", "common" },
        { "Cupid", "common" },
        { "Curse", "common" },
        { "Cutter", "common" },
        { "DamageMultiplier", "common" },
        { "DeadHand", "common" },
        { "Deaf", "common" },
        { "DecoyDummy", "common" },
        { "Disarm", "common" },
        { "Echo", "common" },
        { "Eclipse", "common" },
        { "Evolution", "common" },
        { "Fireball", "common" },
        { "FogOfWar", "common" },
        { "Frostmourne", "common" },
        { "Gaia", "common" },
        { "Gargoyle", "common" },
        { "GunHealer", "common" },
        { "HangedMan", "common" },
        { "HighGravity", "common" },
        { "HotPotato", "common" },
        { "IncreaseSpeed", "common" },
        { "InfiniteAmmo", "common" },
        { "InfoHole", "common" },
        { "IronHead", "common" },
        { "Jammer", "common" },
        { "Jester", "common" },
        { "JumpHeal", "common" },
        { "Karma", "common" },
        { "LastStand", "common" },
        { "LoanShark", "common" },
        { "LongerFlashes", "common" },
        { "Lottery", "common" },
        { "Lucky", "common" },
        { "Miser", "common" },
        { "NoExplosives", "common" },
        { "NoRecoil", "common" },
        { "Overheat", "common" },
        { "Paladin", "common" },
        { "Payback", "common" },
        { "Pickpocket", "common" },
        { "PistolMaster", "common" },
        { "Plague", "common" },
        { "PoisonBlade", "common" },
        { "Priest", "common" },
        { "RadarJammer", "common" },
        { "Redemption", "common" },
        { "Regeneration", "common" },
        { "ReloadGap", "common" },
        { "SacrificeSelf", "common" },
        { "ShadowWarrior", "common" },
        { "SlyFox", "common" },
        { "Synced", "common" },
        { "Teneril", "common" },
        { "Thorns", "common" },
        { "ThunderChain", "common" },
        { "ToxicSmoke", "common" },
        { "Traitor", "common" },
        { "Trickster", "common" },
        { "WeaponRoulette", "common" },
        { "Wolf", "common" },

    };
}
